# Generated by Django 5.1.4 on 2025-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
